import { SignInButton, SignedOut, SignedIn, UserButton } from "@clerk/nextjs";
import Head from "next/head";
import { usePathname } from "next/navigation";

export default function Home() {
  const pathname = usePathname()


  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-black">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">

          <SignedOut>
            <SignInButton mode="modal" afterSignInUrl={pathname} afterSignUpUrl={pathname}>

              <button className="border border-white rounded-full p-4 text-white">
                sign in
              </button>
            </SignInButton>
          </SignedOut>
          <SignedIn>
            <UserButton />
          </SignedIn>



        </div>
      </main>
    </>
  );
}
